FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libgsl-dev

COPY . /repo
WORKDIR /repo/src/build
RUN cmake ..
RUN make -j8
